#Site options
name: Kaos Blog
email: adm@kaos.com.br
baseurl: ""
url: "http://localhost:3000"
facebook: 
  publisher: https://www.facebook.com/fratkaos/

disqus: kaos-blog-1
# Build Options
markdown: kramdown
permalink: /:title/
lang: pt_BR
plugins:
- jekyll-seo-tag
- jekyll-paginate

paginate: 4
paginate_path: /noticias/page-:num/

exclude: ['*.json', 'src', 'node_modules','gulpfile.js','Gemfile','Gemfile.lock','README.md']
include: ['_pages']